### ISSUE TITLE
Accept Symfony 6.* (or 6.4 at least)

### ISSUE THREAD

**Issue by florentdestremau** [danielburger1337/scheb-2fa-email#2]
The `composer.json` file only accepts ^7.0 for symfony packages, is there a hard incompatibility for supporting earlier versions of Symfony, in particular the current LTS ?

**Comment by danielburger1337** [comment]
I don't think there is a hard incompatibility, I will look into it!

**Comment by DjLeChuck** [comment]
👋🏻 Hi,

Have you an estimation time for merging the branch?
I'm successfully using it on a 6.4, but having it as a dev dependency make me feels bad. 😄

**Comment by danielburger1337** [comment]
> 👋🏻 Hi,
> 
> Have you an estimation time for merging the branch? I'm successfully using it on a 6.4, but having it as a dev dependency make me feels bad. 😄

Just released it as v1.1.0. Sorry for the small delay!
